/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FadeIn: typeof import('./src/components/transition/FadeIn.vue')['default']
    FullScreen: typeof import('./src/components/fullscreen/FullScreen.vue')['default']
    Nav: typeof import('./src/components/nav/Nav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
